DOWNLOAD_TAG_VER: v3.7.0
META:
  TITLE: ej4ql8r
  AUTHOR: ej4ql8r
  DESCRIPTION: Mowfows Beware! Good times ahead! Just a noob lost in the sauce.
  ICON_URL: favicon.png
  THEME: dark
BIO:
  ICON_URL: icon.png
  TITLE: ej4ql8r
  DESCRIPTION: Mowfows Beware! Good times ahead! Just a noob lost in the sauce.
  FOOTER: You got GOT by a noob!
BASE_SHORT_URL: ""
ENABLE_REDIRECTS: true
LINKS:
  - brand: discord
    icon: discord
    name: Discord
    link: /discord
    redirects:
      - src: /discord
        dest: https://discord.gg/7M47wRWfu
        code: 308
  - brand: twitch
    icon: twitch
    name: Twitch
    link: /tv
    redirects:
      - src: /tv
        dest: https://www.twitch.tv/ej4ql8r
        code: 308
  - brand: kick
    icon: kick
    name: Kick
    link: /kick
    redirects:
      - src: /kick
        dest: https://www.kick.com/ej4ql8r
        code: 308
  - brand: tiktok
    icon: tiktok
    name: TitKok
    link: /tiktok
    redirects:
      - src: /tiktok
        dest: https://www.tiktok.com/@ej4ql8rgaming
        code: 308
      - src: /tk
        dest: https://www.tiktok.com/@ej4ql8rgaming

        code: 308
